language: php
sudo: true
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
before_install:
  - composer selfupdate
install:
  - composer install
  - sudo chmod 0444 ./test/_data/non.readable.txt
  - sudo chown www-data:www-data ./test/_data/non.readable.txt
after_script:
  - CODECLIMATE_REPO_TOKEN=badc29b931533dd8efb832ffff7bf8dbc31486290ae3b1c81d38fa677795ffaf ./vendor/bin/test-reporter
