# general
# @link http://docs.travis-ci.com/user/customizing-the-build/
language: php
sudo: true

# target php versions
# no php 5.3 as it is no longer maintained
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

# allow HHVM to fail
matrix:
  allow_failures:
    - php: hhvm

# move CodeClimate token here
addons:
  code_climate:
    repo_token: badc29b931533dd8efb832ffff7bf8dbc31486290ae3b1c81d38fa677795ffaf

# update composer dist
before_install:
  - composer selfupdate

# install dependancies
install:
  - composer update

# prepare test data
before_script:
  - sudo sh ./bin/prepare-for-test.sh

# what are we doing as build?
script:
  - if [[ "hhvm" == "$TRAVIS_PHP_VERSION" ]]; then ./vendor/bin/phpunit -c ./test/phpunit-hhvm.xml ; else ./vendor/bin/phpunit ; fi

# report code coverage
after_script:
  # show coverage in build logs
  - if [[ "hhvm" == "$TRAVIS_PHP_VERSION" ]]; then echo "HHVM - skip coverage reporter" && exit 0 ; else php -f ./bin/CoverageChecker.php ./build/logs/clover.xml 5 ; fi
  # send coverage to CodeClimate
  - if [[ "hhvm" == "$TRAVIS_PHP_VERSION" ]]; then echo "HHVM - skip coverage reporter" && exit 0 ; else ./vendor/bin/test-reporter ; fi
